[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install -y unzip",
    "PB_REL=\"https://github.com/protocolbuffers/protobuf/releases\";curl -LO $PB_REL/download/v28.2/protoc-28.2-linux-x86_64.zip",
    "unzip protoc-28.2-linux-x86_64.zip -d $HOME/.local",
    "export PATH=\"$PATH:$HOME/.local/bin\";chmod +x $HOME/.local/bin/protoc",
    "protoc --version",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install -y unzip",
    "PB_REL=\"https://github.com/protocolbuffers/protobuf/releases\";curl -LO $PB_REL/download/v28.2/protoc-28.2-linux-x86_64.zip",
    "unzip protoc-28.2-linux-x86_64.zip -d $HOME/.local",
    "export PATH=\"$PATH:$HOME/.local/bin\";chmod +x $HOME/.local/bin/protoc",
    "protoc --version",
]