[target.x86_64-unknown-linux-musl]
pre-build = [
    "PB_REL=\"https://github.com/protocolbuffers/protobuf/releases\";curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip",
    "unzip protoc-28.2-linux-x86_64.zip -d $HOME/.local",
    "export PATH=\"$PATH:$HOME/.local/bin\"",
    "protoc --version",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "PB_REL=\"https://github.com/protocolbuffers/protobuf/releases\";curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-aarch_64.zip",
    "unzip protoc-28.2-linux-x86_64.zip -d $HOME/.local",
    "export PATH=\"$PATH:$HOME/.local/bin\"",
    "protoc --version",
]